### [ DragonWand ] ###

# Jai Shree Ram But I Am Also From Nepal
# Please Add EconomyAPI And FormAPI And FormImagesFix Plugin
# You Can Adjust Price Here:
# Subscribe My Channel 'LunarBoyMCPE'

Dirt_Wand_Price: 10000000
Stone_Wand_Price: 10000000
Bricks_Wand_Price: 10000000
Glass_Wand_Price: 10000000
Quartz_Wand_Price: 10000000
Wood_Wand_Price: 10000000

# Don't Add M or K
# Enjoy Plugin
